data:
  random_state: 42
  split_config:
    test_ratio: 0.15
    train_ratio: 0.7
    val_ratio: 0.15
evaluation:
  metrics:
  - dice
  - iou
  - accuracy
  - precision
  - recall
  - f1
  num_samples: 5
  threshold: 0.5
  visualization:
    enabled: true
    plot_gradcam: true
    plot_wrong_predictions: true
logging:
  log_every_n_steps: 10
  use_wandb: false
  wandb_project: glaucoma-detection
model:
  in_channels: 3
  num_classes: 1
  pretrained: true
paths: {}
pipeline:
  description: Default pipeline run
  force: false
  steps:
  - extract
  - load
  - clean
  - preprocess
  - train
  - evaluate
preprocessing:
  augmentation:
    enabled: true
    height_shift_range: 0.1
    horizontal_flip: true
    rotation_range: 15
    shear_range: 0.1
    vertical_flip: false
    width_shift_range: 0.1
    zoom_range: 0.1
  image_channels: 3
  mode: segmentation
  normalization: imagenet
training:
  accumulate_grad_batches: 1
  checkpointing:
    enabled: true
    mode: min
    monitor: val_loss
    save_top_k: 3
  early_stopping:
    enabled: true
    min_delta: 0.001
    mode: min
    monitor: val_loss
    patience: 10
  gpu_ids:
  - 0
  gradient_clip_val: 0.0
  learning_rate: 0.001
  loss_function: combined
  lr_scheduler:
    enabled: true
    factor: 0.1
    min_lr: 1.0e-06
    monitor: val_loss
    patience: 5
  num_workers: 4
  optimizer: adam
  precision: 32-true
  use_class_weights: true
  use_gpu: true
